apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doc-rag-api.fullname" . }}
  labels:
    {{- include "doc-rag-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "doc-rag-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "doc-rag-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "doc-rag-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.appConfig.port }}"
            - name: DATABASE_URL
              value: {{ .Values.appConfig.databaseUrl | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "doc-rag-api.fullname" . }}
                  key: jwt-secret
            - name: JWT_ALGORITHM
              value: {{ .Values.appConfig.jwtAlgorithm | quote }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.appConfig.s3BucketName | quote }}
            - name: AWS_REGION
              value: {{ .Values.appConfig.awsRegion | quote }}
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "doc-rag-api.fullname" . }}
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "doc-rag-api.fullname" . }}
                  key: aws-secret-access-key
          livenessProbe:
            httpGet:
              path: /test
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /test
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: doc-rag-storage
              mountPath: /app/data
      volumes:
        - name: doc-rag-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "doc-rag-api.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 